eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Monster\ Manual\ Bestiary\ 2.6.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Curse\ of\ Strahd\ Bestiary\ 1.2.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Hoard\ of\ the\ Dragon\ Queen\ Bestiary\ 1.3.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Out\ of\ the\ Abyss\ 1.4.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Phandelver\ Bestiary\ 1.3.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Princes\ of\ the\ Apocalypse\ Bestiary\ 1.3.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Storm\ King\'s\ Thunder\ Bestiary\ 1.1.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/The\ Rise\ of\ Tiamat\ Bestiary\ 1.3.0.xml"
eval "ruby importers/monsters.rb ~/Documents/DandD\ App\ Files/Bestiary/Volo\'s\ Bestiary\ 1.1.0.xml"
